workers=50

[db]
domain="1,2,4,8,14,17,22"
name="bill"
user="switchd"
password="xxxxx"
sid="xxx.xxx.xx:3306"


[default]
community="xxxxxxx"

[default.oids]
bytes_send="1.3.6.1.2.1.31.1.1.1.10"
bytes_recv="1.3.6.1.2.1.31.1.1.1.6"
error_in="1.3.6.1.2.1.2.2.1.14"

[influx]
hosts = [
	"127.0.0.1:8089"
]

[[models]]
name="DES-2108"

[[models]]
name="DES-3010G"

[[models]]
name="DES 3028"

[[models]]
name="DES-1210"

[[models]]
name="DGS-3200"

[[models]]
name="DGS-3120"

[[models]]
name="DES-3200-28"

[[models]]
name="DES_1210-28/ME"

[[models]]
name="DGS-3620-28"

[[models]]
name="DGS-3420-26SC"

[[models]]
name="DES 1210-10/ME"

[[models]]
name="DES-1228/ME"

[[models]]
name="DGS1100-x/ME"

[[models]]
name="DGS-3000-28SC"

[[models]]
name="DGS-1210-10P"

[[models]]
name="DES 1210-28/ME-2"

[[models]]
name="DGS-1210-12TS/ME"

[[models]]
name="DES-3200-18"

[[models]]
name="DES-3200-10"

[[models]]
name="DES-3200-28/C1"

[[models]]
name="DGS-3420-28TC"

[[models]]
name="DGS-3420-28SC"

[[models]]
name="DES-3200-10/C1"

[[models]]
name="DGS-1210-28/ME"

[[models]]
name="DGS-1510-28P"

[[models]]
name="DES 1210-28/ME"

[[models]]
name="DGS 1100-06 ME"

[[models]]
name="DES-1210-52/ME/C1"

[[models]]
name="S2990G-24FX"

[[models]]
name="S2990G-24FX-UPS"